import type { PriorityRouteContent } from "@/types/content";

const pending = (
  path: string,
  title: string,
  eyebrow: string,
  heading: string,
  intro: string,
  panels: PriorityRouteContent["panels"],
  nextAction?: PriorityRouteContent["nextAction"],
): PriorityRouteContent => ({
  seo: {
    path,
    title: `${title} | Living Message Church`,
    description: `${title} information for Living Message Church.`,
    noIndex: true,
  },
  eyebrow,
  title: heading,
  intro,
  statusLabel: "Content review in progress",
  statusBody:
    "This page structure is ready, but the church-specific details are intentionally withheld until the named content owner approves them.",
  panels,
  nextAction,
});

export const priorityRouteContent = {
  about: pending(
    "/about",
    "About",
    "About",
    "About Living Message Church.",
    "A focused place for the church’s approved story, identity, and leadership pathways.",
    [
      { number: "01", title: "Story and identity", body: "The approved history, name origin, and church-family language will live here after pastoral review." },
      { number: "02", title: "Beliefs", body: "Read the church’s complete current doctrinal statement and Scripture references.", href: "/about/beliefs", linkLabel: "Open beliefs" },
      { number: "03", title: "Leadership", body: "Meet the pastors, elders, deacons, and ministry leaders serving Living Message Church.", href: "/about/leadership", linkLabel: "Meet our team" },
    ],
    { label: "Plan your visit", href: "/plan-your-visit", style: "primary" },
  ),
  connect: pending(
    "/connect",
    "Connect",
    "Connect",
    "A clear path toward connection.",
    "Each pathway below has a dedicated route, but schedules, leaders, age ranges, and registration details remain unpublished until approved.",
    [
      { number: "01", title: "Kids", body: "A future practical guide to ages, check-in, safety, and first-visit preparation.", href: "/connect/kids", linkLabel: "Open Kids" },
      { number: "02", title: "Youth", body: "A future guide to the verified youth ministry, audience, gatherings, and leadership.", href: "/connect/youth", linkLabel: "Open Youth" },
      { number: "03", title: "Young Adults", body: "A future guide to approved young-adult connection opportunities.", href: "/connect/young-adults", linkLabel: "Open Young Adults" },
      { number: "04", title: "Groups", body: "A future directory of current, approved groups and connection rhythms.", href: "/connect/groups", linkLabel: "Open Groups" },
      { number: "05", title: "Next Steps Class", body: "A future guide to the confirmed connection, service, and growth pathway.", href: "/connect/next-steps", linkLabel: "Open Next Steps Class" },
    ],
    { label: "Plan your visit", href: "/plan-your-visit", style: "primary" },
  ),
  kids: pending(
    "/connect/kids",
    "Kids",
    "Connect",
    "A first visit should feel prepared.",
    "This route will prioritize accurate ages, check-in, safety, accessibility, allergies, and pickup information after safeguarding approval.",
    [
      { number: "01", title: "Ages and rooms", body: "The legacy site conflicts on the starting age, so no age range is published yet." },
      { number: "02", title: "Check-in and pickup", body: "The complete approved arrival, label, security, and pickup process will be documented here." },
      { number: "03", title: "Safety and access", body: "Approved screening, allergy, accommodation, and accessibility information is required before publication." },
    ],
    { label: "Plan your visit", href: "/plan-your-visit", style: "primary" },
  ),
  youth: pending(
    "/connect/youth",
    "Youth",
    "Connect",
    "A dedicated place for verified youth information.",
    "The audit found historical youth references but no complete current ministry record.",
    [
      { number: "01", title: "Audience", body: "Approved ages or grades are required before this route can publish." },
      { number: "02", title: "Gatherings", body: "Current cadence, location, transportation, and registration remain unconfirmed." },
      { number: "03", title: "Safeguarding", body: "Leadership, screening, communication, and guardian expectations require approval." },
    ],
    { label: "Explore Connect", href: "/connect", style: "secondary" },
  ),
  youngAdults: pending(
    "/connect/young-adults",
    "Young Adults",
    "Connect",
    "Connection for young adults.",
    "A current ministry name appears in the audited roster, but its leader, audience, schedule, and location are not approved for publication.",
    [
      { number: "01", title: "Who it serves", body: "The approved audience and age definition will be stated clearly." },
      { number: "02", title: "How to connect", body: "Only a current cadence, location, and contact path will be published." },
      { number: "03", title: "What to expect", body: "Approved gathering and discipleship details will replace this holding content." },
    ],
    { label: "Explore Connect", href: "/connect", style: "secondary" },
  ),
  groups: pending(
    "/connect/groups",
    "Groups",
    "Connect",
    "Life together, with accurate details.",
    "Historical group names are not being presented as current. This route is ready for an approved, maintainable group directory.",
    [
      { number: "01", title: "Current groups", body: "Each published group will require an owner, audience, cadence, location, and status." },
      { number: "02", title: "Find a fit", body: "The final experience will help visitors choose by life stage or purpose without exposing private member data." },
      { number: "03", title: "External handoff", body: "Enrollment will remain with the approved specialist church system when confirmed." },
    ],
    { label: "Explore Connect", href: "/connect", style: "secondary" },
  ),
  outreach: pending(
    "/outreach",
    "Outreach",
    "Outreach",
    "Outreach, represented responsibly.",
    "The current site contains meaningful outreach material, but the organizational relationship, program details, impact claims, and external links still require owner approval.",
    [
      { number: "01", title: "Local impact", body: "Only current, approved programs and eligibility information will publish." },
      { number: "02", title: "Partners", body: "Descriptions, relationships, links, and logo permissions require confirmation for every partner." },
      { number: "03", title: "Ways to help", body: "Volunteer and donation actions will link directly to their approved specialist destinations." },
    ],
    { label: "Contact the church", href: "/contact", style: "secondary" },
  ),
  give: pending(
    "/give",
    "Give",
    "Give",
    "Giving with a clear, trusted handoff.",
    "The public route will explain giving and link to the specialist provider only after finance confirms the account destination and stewardship copy.",
    [
      { number: "01", title: "Why give", body: "Pastoral and finance-approved stewardship language is required." },
      { number: "02", title: "Secure provider", body: "The website will never collect or process payment-card or bank details." },
      { number: "03", title: "Help and receipts", body: "An approved finance contact and recurring-gift guidance will be published here." },
    ],
    { label: "Contact the church", href: "/contact", style: "secondary" },
  ),
};
